on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: nixos
    strategy:
      matrix:
        system:
          - x86_64-linux
        test:
          - treefmt
    env:
      TEST: ${{ matrix.test }}
      SYSTEM: ${{ matrix.system }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run: nix --version
      - name: Run tests
        run: |
          nix build --print-build-logs \
            .#checks."$SYSTEM"."$TEST"
  build:
    runs-on: nixos
    steps:
      - uses: https://git.salame.cl/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run: nix --version
      - name: Build Package
        id: build
        run: |
          nix build --print-build-logs .#
  report-size:
    runs-on: nixos
    needs: build
    steps:
      - uses: https://git.salame.cl/actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - run: nix --version
      - name: Generate size report
        uses: "https://git.salame.cl/jalil/nix-flake-outputs-size@ceab16dddbb0c7da29b3821174cfdaa5bec8670e" # main
        with:
          comment-on-pr: ${{ github.ref_name != 'main' }}
          generate-artifact: ${{ github.ref_name == 'main' }}
          do-comparison: true
          job-name: report-size
