on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: nixos
    strategy:
      matrix:
        system:
          - x86_64-linux
        test:
          - treefmt
    env:
      TEST: ${{ matrix.test }}
      SYSTEM: ${{ matrix.system }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Run tests
        run: |
          nix build --print-build-logs \
            .#checks."$SYSTEM"."$TEST"
  build:
    runs-on: nixos
    outputs:
      outPath: ${{ steps.build.outputs.outPath }}
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Build Package
        id: build
        run: |
          outPath=$(nix build --print-build-logs --print-out-paths .#)
          echo "outPath=packages:site:$outPath" >> "$FORGEJO_OUTPUT"
  report-size:
    runs-on: nixos
    needs: build
    steps:
      - uses: https://git.salame.cl/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: nix --version
      - name: Generate size report
        uses: "https://git.salame.cl/jalil/nix-flake-outputs-size@eb9c1434484fa45d8b442161a6d746478b776702" # main
        with:
          comment-on-pr: ${{ github.ref_name != 'main' }}
          generate-artifact: ${{ github.ref_name == 'main' }}
          do-comparison: true
          job-name: report-size
          prebuilt-derivations: "${{ needs.build.outputs.outPath }}"
